feat: fixing conflicts

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -10,18 +10,38 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v3
+    - uses: actions/checkout@v4
     - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v1
+      uses: docker/setup-buildx-action@v2
     - name: Log in to Docker Hub
-      uses: docker/login-action@v1
+      uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
     - name: Build and push
-      uses: docker/build-push-action@v2
-      with:
-        context: .
-        file: Dockerfile
-        push: true
-        tags: ${{ secrets.DOCKER_USERNAME }}/ophelia_spark:latest
+      run: |
+        set -e  # Exit immediately if a command exits with a non-zero status.
+        
+        REPOSITORY_NAME="ophelia_spark"
+        IMAGE_TAG="latest"
+        DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}"
+        
+        # Full image name including the Docker Hub username
+        FULL_IMAGE_NAME="${DOCKER_USERNAME}/${REPOSITORY_NAME}:${IMAGE_TAG}"
+        
+        # Build the Docker image locally using docker 'buildx' for Apple M1/M2 architectures
+        docker buildx build --platform linux/amd64 -t "${REPOSITORY_NAME}:${IMAGE_TAG}" -f Dockerfile .
+        
+        # Tag the Docker image with the full image name
+        docker tag "${REPOSITORY_NAME}:${IMAGE_TAG}" "${FULL_IMAGE_NAME}"
+        
+        # Push the image to Docker registry
+        if ! docker push "${FULL_IMAGE_NAME}"; then
+          echo "Error: Failed to push the image to ${FULL_IMAGE_NAME}"
+          exit 1
+        fi
+        
+        echo "Image successfully pushed to ${FULL_IMAGE_NAME}"
+        
+        # Clean up Docker system
+        docker system prune -f
